version: '3'
services:


  kafka:
    build: ../kafka
    env_file:
      - .env
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CLIENT_USER=admin
    volumes:
      - kafka-data:/bitnami/kafka
    
  redis:
    image: redis:6.0.5
    volumes:
      - redis-data:/data

  a6tcontroller:
    build: ../controller
    volumes:
      - ../controller/lib:/service/lib
      - ../controller/index.js:/service/index.js
      - ../controller/run.js:/service/run.js

  worker:
    image: node:14
    volumes:
      - ./worker/index.js:/service/index.js


volumes:
  kafka-data:
  redis-data: