version: '3'
services:

  kafka:
    image: ucdlib-pubreg/a6t-kafka:local-dev
    env_file:
      - .env
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CLIENT_USER=admin
    volumes:
      - kafka-data:/bitnami/kafka
    
  redis:
    image: redis:6.0.5
    volumes:
      - redis-data:/data

  a6tcontroller:
    image: ucdlib-pubreg/a6t-controller:local-dev
    volumes:
      - ../controller/lib:/service/lib
      - ../controller/index.js:/service/index.js
      - ../controller/run.js:/service/run.js
      - ../lib/node/lib:/utils/lib
      - ../lib/node/index.js:/utils/index.js
      - ./dag:/etc/a6t/dag
    command: bash -c 'tail -f /dev/null'

  worker:
    image: ucdlib-pubreg/a6t-test-worker:local-dev
    volumes:
      - ./worker/index.js:/service/index.js
      - ../lib/node/lib:/utils/lib
      - ../lib/node/index.js:/utils/index.js
    command: bash -c 'tail -f /dev/null'

volumes:
  kafka-data:
  redis-data: